export const APPLICATION_INITIALIZED = 'APPLICATION_INITIALIZED';
export const FETCH_CONFIG_COMPLETED = 'FETCH_CONFIG_COMPLETED';
export const FETCH_CONFIG_ERROR = 'FETCH_CONFIG_ERROR';
export const FETCH_FEATURE_FLAGS_COMPLETED = 'FETCH_FEATURE_FLAGS_COMPLETED';
export const FETCH_FEATURE_FLAGS_UPDATED = 'FETCH_FEATURE_FLAGS_UPDATED';
export const FETCH_FEATURE_FLAGS_ERROR = 'FETCH_FEATURE_FLAGS_ERROR';
